2022-03-28 14:56:51.132 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 14:57:01.142 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:08:22.678 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:08:32.682 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:09:24.345 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:09:34.360 [http-nio-8001-exec-7] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:09:52.790 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:10:02.795 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:12:05.108 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:12:15.121 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:13:25.289 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:13:35.303 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:13:45.624 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:15:41.476 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:15:51.485 [http-nio-8001-exec-7] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:17:23.516 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:17:33.531 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:20:19.076 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:20:29.089 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:20:59.284 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:21:09.295 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:21:46.016 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:21:56.020 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:28:02.075 [http-nio-8001-exec-7] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:28:12.082 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:28:25.835 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:34:12.156 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:34:22.163 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:47:46.433 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 15:47:56.435 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:12:20.171 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:12:30.187 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:14:00.963 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:17:43.391 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:17:53.399 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:19:04.280 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:19:14.294 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:19:45.882 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:20:33.316 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:20:43.321 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:20:53.331 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:21:03.334 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:00.922 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:10.937 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:20.954 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:30.966 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:40.970 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:24:50.982 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:00.986 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:11.001 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:21.007 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:31.014 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:41.021 [http-nio-8001-exec-7] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:25:51.031 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:01.036 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:11.050 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:21.066 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:31.080 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:41.097 [http-nio-8001-exec-12] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:26:51.112 [http-nio-8001-exec-11] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:27:01.116 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:27:11.125 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:31:30.651 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:33:26.812 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:36:41.722 [http-nio-8001-exec-10] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 16:36:51.735 [http-nio-8001-exec-6] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:08:51.356 [ThreadPoolTaskScheduler-1] ERROR o.s.cloud.alibaba.nacos.discovery.NacosWatch -
                Error watching Nacos Service change
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([localhost:8848]) tried: failed to req API:http://localhost:8848/nacos/v1/ns/service/list. code:500 msg: java.net.ConnectException: Connection refused: connect
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:346)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:294)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:276)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:252)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:525)
	at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-28 22:08:51.785 [main] ERROR o.s.c.alibaba.nacos.registry.NacosServiceRegistry -
                nacos registry, service-edu register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='localhost:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='service-edu', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.31.42', networkInterface='', port=8001, secure=false, accessKey='', secretKey=''}},
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:500 msg: java.net.ConnectException: Connection refused: connect
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:186)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:298)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:279)
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:63)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239)
	at org.springframework.cloud.alibaba.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:74)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.atguigu.eduservice.EduApplication8001.main(EduApplication8001.java:19)
2022-03-28 22:11:14.414 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:11:24.423 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:11:34.434 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:11:44.438 [http-nio-8001-exec-3] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:19:36.818 [http-nio-8001-exec-2] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:19:46.829 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:47:32.376 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:47:42.391 [http-nio-8001-exec-5] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:47:52.403 [http-nio-8001-exec-1] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:48:09.627 [http-nio-8001-exec-4] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:48:19.643 [http-nio-8001-exec-7] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:49:38.300 [http-nio-8001-exec-9] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
2022-03-28 22:49:48.302 [http-nio-8001-exec-8] ERROR c.a.servicebase.handler.GlobalExceptionHandler -
                Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.31.121:6379
